// Code generated by service-export(1.0.0). DO NOT EDIT.
// source: service.go

package example

import "context"

var defaultService Service

func Register(s Service) {
	defaultService = s
}

func GetExample(ctx context.Context, req *GetExampleRequest) (resp *GetExampleResponse, err error) {
	if defaultService == nil {
		panic("调用模块方法: example.GetExample 失败，服务未注册")
	}
	v1, v2 := defaultService.GetExample(ctx, req)
	return v1, v2
}
